version: '3'
services:
  php-easy-bbs2_app:
    build:
      context: ./docker/app
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
  php-easy-bbs2_db:
    build:
      context: ./docker/db
    volumes:
      - ./docker/db/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbs
      - TZ=Asia/Tokyo
