version: '3'
services:
  php-easy-bbs2_app:
    build:
      context: ./docker/app
    volumes:
      - ./html:/var/www/html
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: bbs.yuzupi.com
      LETSENCRYPT_HOST: bbs.yuzupi.com
      LETSENCRYPT_EMAIL: nurugamer2@gmail.com
  php-easy-bbs2_db:
    build:
      context: ./docker/db
    volumes:
      - ./docker/db/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbs
      - TZ=Asia/Tokyo
networks:
  default:
    external:
      name: nginx-proxy
